package pojo;
// Generated 2/01/2016 05:27:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set<Tproducto> tproductos = new HashSet<Tproducto>(0);

    public Categoria() {
    }

	
    public Categoria(String nombre) {
        this.nombre = nombre;
    }
    public Categoria(String nombre, Set<Tproducto> tproductos) {
       this.nombre = nombre;
       this.tproductos = tproductos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Tproducto> getTproductos() {
        return this.tproductos;
    }
    
    public void setTproductos(Set<Tproducto> tproductos) {
        this.tproductos = tproductos;
    }




}


