package pojo;
// Generated 2/01/2016 05:27:14 PM by Hibernate Tools 4.3.1



/**
 * Movimiento generated by hbm2java
 */
public class Movimiento  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String tipo;

    public Movimiento() {
    }

	
    public Movimiento(String nombre) {
        this.nombre = nombre;
    }
    public Movimiento(String nombre, String tipo) {
       this.nombre = nombre;
       this.tipo = tipo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


