package pojo;
// Generated 2/01/2016 05:27:14 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tventa generated by hbm2java
 */
public class Tventa  implements java.io.Serializable {


     private Integer idVenta;
     private Usuario usuario;
     private BigDecimal precioVentaTotal;
     private Date fechaRegistro;
     private Set<Tventadetalle> tventadetalles = new HashSet<Tventadetalle>(0);

    public Tventa() {
    }

	
    public Tventa(Usuario usuario, BigDecimal precioVentaTotal, Date fechaRegistro) {
        this.usuario = usuario;
        this.precioVentaTotal = precioVentaTotal;
        this.fechaRegistro = fechaRegistro;
    }
    public Tventa(Usuario usuario, BigDecimal precioVentaTotal, Date fechaRegistro, Set<Tventadetalle> tventadetalles) {
       this.usuario = usuario;
       this.precioVentaTotal = precioVentaTotal;
       this.fechaRegistro = fechaRegistro;
       this.tventadetalles = tventadetalles;
    }
   
    public Integer getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public BigDecimal getPrecioVentaTotal() {
        return this.precioVentaTotal;
    }
    
    public void setPrecioVentaTotal(BigDecimal precioVentaTotal) {
        this.precioVentaTotal = precioVentaTotal;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set<Tventadetalle> getTventadetalles() {
        return this.tventadetalles;
    }
    
    public void setTventadetalles(Set<Tventadetalle> tventadetalles) {
        this.tventadetalles = tventadetalles;
    }




}


