package pojo;
// Generated 2/01/2016 05:27:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private int nivel;
     private String nombre;
     private String password;
     private Set<Egreso> egresos = new HashSet<Egreso>(0);
     private Set<Tventa> tventas = new HashSet<Tventa>(0);
     private Set<Ingreso> ingresos = new HashSet<Ingreso>(0);

    public Usuario() {
    }

	
    public Usuario(int nivel, String nombre, String password) {
        this.nivel = nivel;
        this.nombre = nombre;
        this.password = password;
    }
    public Usuario(int nivel, String nombre, String password, Set<Egreso> egresos, Set<Tventa> tventas, Set<Ingreso> ingresos) {
       this.nivel = nivel;
       this.nombre = nombre;
       this.password = password;
       this.egresos = egresos;
       this.tventas = tventas;
       this.ingresos = ingresos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getNivel() {
        return this.nivel;
    }
    
    public void setNivel(int nivel) {
        this.nivel = nivel;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<Egreso> getEgresos() {
        return this.egresos;
    }
    
    public void setEgresos(Set<Egreso> egresos) {
        this.egresos = egresos;
    }
    public Set<Tventa> getTventas() {
        return this.tventas;
    }
    
    public void setTventas(Set<Tventa> tventas) {
        this.tventas = tventas;
    }
    public Set<Ingreso> getIngresos() {
        return this.ingresos;
    }
    
    public void setIngresos(Set<Ingreso> ingresos) {
        this.ingresos = ingresos;
    }




}


