/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.UIManager;
import pojo.Usuario;

/**
 *
 * @author mq12
 */
public class Principal extends javax.swing.JFrame {
  public  Usuario usuario = new Usuario();
    /**
     * Creates new form Principal
     */
    public Principal() {
        try {
            
             UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            
            this.setExtendedState(this.MAXIMIZED_BOTH);
              initComponents();
              jButtonAltaProducto.setEnabled(false);
            jButtonCerrarSecion.setEnabled(false);
            jButtonCrearCategoria.setEnabled(false);
            jButtonCrearMovimiento.setEnabled(false);
            jButtonCrearUsuario.setEnabled(false);
            jButtonEgreso.setEnabled(false);
            jButtonIngreso.setEnabled(false);
            jButtonMisVEntas.setEnabled(false);
            jButtonModificarProducto.setEnabled(false);
            jButtonModificarUsuario.setEnabled(false);
            jButtonSalor.setEnabled(false);
            jButtonTotal.setEnabled(false);
            jButtonVentas.setEnabled(false);
            jButtonIngresoEgreso.setEnabled(false);
            jMenu1.setEnabled(false);
            jMenu2.setEnabled(false);
            jMenuAdministrador.setEnabled(false);
            jMenuMisVentas.setEnabled(false);
            jMenuReportes.setEnabled(false);
            jMenuMovimiento.setEnabled(false);
            jButtonInventario.setEnabled(false);
            jButtonVender.setEnabled(false);
             Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/database.png"));
            setIconImage(icon);
            setVisible(true);
        } catch (Exception e) {
        }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButtonVender = new javax.swing.JButton();
        jButtonAltaProducto = new javax.swing.JButton();
        jButtonModificarProducto = new javax.swing.JButton();
        jButtonCrearCategoria = new javax.swing.JButton();
        jButtonEgreso = new javax.swing.JButton();
        jButtonIngreso = new javax.swing.JButton();
        jButtonCrearMovimiento = new javax.swing.JButton();
        jButtonMisVEntas = new javax.swing.JButton();
        jButtonCrearUsuario = new javax.swing.JButton();
        jButtonModificarUsuario = new javax.swing.JButton();
        jButtonTotal = new javax.swing.JButton();
        jButtonVentas = new javax.swing.JButton();
        jButtonIngresoEgreso = new javax.swing.JButton();
        jButtonInventario = new javax.swing.JButton();
        jButtonCerrarSecion = new javax.swing.JButton();
        jButtonSalor = new javax.swing.JButton();
        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCerrarSeccion = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemAltaProducto = new javax.swing.JMenuItem();
        jMenuItemModificarProducto = new javax.swing.JMenuItem();
        jMenuItemCrearCategoria = new javax.swing.JMenuItem();
        jMenuMovimiento = new javax.swing.JMenu();
        jMenuItemEgreso = new javax.swing.JMenuItem();
        jMenuItemIngreso = new javax.swing.JMenuItem();
        jMenuItemCrearMovimiento = new javax.swing.JMenuItem();
        jMenuMisVentas = new javax.swing.JMenu();
        jMenuItemMisVentas = new javax.swing.JMenuItem();
        jMenuAdministrador = new javax.swing.JMenu();
        jMenuItemCrearUsuario = new javax.swing.JMenuItem();
        jMenuItemModificarUsuario = new javax.swing.JMenuItem();
        jMenuReportes = new javax.swing.JMenu();
        jMenuItemTotal = new javax.swing.JMenuItem();
        jMenuItemVentasDetalle = new javax.swing.JMenuItem();
        jMenuItemingresosEgresos = new javax.swing.JMenuItem();
        jMenuItemInventarioPapeleria = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButtonVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vender.jpg"))); // NOI18N
        jButtonVender.setText("Vender");
        jButtonVender.setFocusable(false);
        jButtonVender.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVender.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonVender);

        jButtonAltaProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/altaProducto64x64.png"))); // NOI18N
        jButtonAltaProducto.setText("Producto");
        jButtonAltaProducto.setFocusable(false);
        jButtonAltaProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAltaProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonAltaProducto);

        jButtonModificarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modificarProduccto64x64.png"))); // NOI18N
        jButtonModificarProducto.setText("Modificar");
        jButtonModificarProducto.setFocusable(false);
        jButtonModificarProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonModificarProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonModificarProducto);

        jButtonCrearCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/crearCategoria64x64.png"))); // NOI18N
        jButtonCrearCategoria.setText("Crear Cat.");
        jButtonCrearCategoria.setFocusable(false);
        jButtonCrearCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCrearCategoria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonCrearCategoria);

        jButtonEgreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/egreso64x64.png"))); // NOI18N
        jButtonEgreso.setText("Egreso");
        jButtonEgreso.setFocusable(false);
        jButtonEgreso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEgreso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonEgreso);

        jButtonIngreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ingreso64x64.png"))); // NOI18N
        jButtonIngreso.setText("Ingreso");
        jButtonIngreso.setFocusable(false);
        jButtonIngreso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonIngreso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonIngreso);

        jButtonCrearMovimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/crearMovimiento64x64.png"))); // NOI18N
        jButtonCrearMovimiento.setText("Crear Mov.");
        jButtonCrearMovimiento.setFocusable(false);
        jButtonCrearMovimiento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCrearMovimiento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCrearMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearMovimientoActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonCrearMovimiento);

        jButtonMisVEntas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/misVentas64x64.png"))); // NOI18N
        jButtonMisVEntas.setText("Mis Ventas");
        jButtonMisVEntas.setFocusable(false);
        jButtonMisVEntas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonMisVEntas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonMisVEntas);

        jButtonCrearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/crearUsuario64x64.png"))); // NOI18N
        jButtonCrearUsuario.setText("Alta Usua.");
        jButtonCrearUsuario.setFocusable(false);
        jButtonCrearUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCrearUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonCrearUsuario);

        jButtonModificarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modificarUsuario64x64.png"))); // NOI18N
        jButtonModificarUsuario.setText("Mod. usuario");
        jButtonModificarUsuario.setFocusable(false);
        jButtonModificarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonModificarUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonModificarUsuario);

        jButtonTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/total64x64.png"))); // NOI18N
        jButtonTotal.setText("Rep. Total");
        jButtonTotal.setFocusable(false);
        jButtonTotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTotal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonTotal);

        jButtonVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ventas64x64.png"))); // NOI18N
        jButtonVentas.setText("Ventas");
        jButtonVentas.setFocusable(false);
        jButtonVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonVentas);

        jButtonIngresoEgreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ingresoEgreso64x64.png"))); // NOI18N
        jButtonIngresoEgreso.setText("Ing/Egreso");
        jButtonIngresoEgreso.setFocusable(false);
        jButtonIngresoEgreso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonIngresoEgreso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonIngresoEgreso);

        jButtonInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inventario.png"))); // NOI18N
        jButtonInventario.setText("Inven.");
        jButtonInventario.setFocusable(false);
        jButtonInventario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonInventario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonInventario);

        jButtonCerrarSecion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login64X64.png"))); // NOI18N
        jButtonCerrarSecion.setText("Cerrar");
        jButtonCerrarSecion.setFocusable(false);
        jButtonCerrarSecion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCerrarSecion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonCerrarSecion);

        jButtonSalor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salir64x64.jpg"))); // NOI18N
        jButtonSalor.setText("Salir");
        jButtonSalor.setFocusable(false);
        jButtonSalor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSalor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonSalor);

        jDesktopPane.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        jMenuItemCerrarSeccion.setText("Cerrar Seccion");
        jMenu1.add(jMenuItemCerrarSeccion);

        jMenuItemSalir.setText("Salir");
        jMenu1.add(jMenuItemSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Articulos");

        jMenuItemAltaProducto.setText("Alta producto");
        jMenu2.add(jMenuItemAltaProducto);

        jMenuItemModificarProducto.setText("Modificar Producto");
        jMenu2.add(jMenuItemModificarProducto);

        jMenuItemCrearCategoria.setText("Crear Categoria");
        jMenu2.add(jMenuItemCrearCategoria);

        jMenuBar1.add(jMenu2);

        jMenuMovimiento.setText("Movimiento");

        jMenuItemEgreso.setText("Egreso");
        jMenuMovimiento.add(jMenuItemEgreso);

        jMenuItemIngreso.setText("Ingreso");
        jMenuMovimiento.add(jMenuItemIngreso);

        jMenuItemCrearMovimiento.setText("Crear Movimiento");
        jMenuMovimiento.add(jMenuItemCrearMovimiento);

        jMenuBar1.add(jMenuMovimiento);

        jMenuMisVentas.setText("Mis ventas");

        jMenuItemMisVentas.setText("Mis ventas");
        jMenuMisVentas.add(jMenuItemMisVentas);

        jMenuBar1.add(jMenuMisVentas);

        jMenuAdministrador.setText("Administrador");

        jMenuItemCrearUsuario.setText("Crear Usuario");
        jMenuAdministrador.add(jMenuItemCrearUsuario);

        jMenuItemModificarUsuario.setText("Modificar Usuario");
        jMenuAdministrador.add(jMenuItemModificarUsuario);

        jMenuBar1.add(jMenuAdministrador);

        jMenuReportes.setText("Reportes");

        jMenuItemTotal.setText("Total");
        jMenuReportes.add(jMenuItemTotal);

        jMenuItemVentasDetalle.setText("Ventas");
        jMenuReportes.add(jMenuItemVentasDetalle);

        jMenuItemingresosEgresos.setText("ingresos/egresos");
        jMenuReportes.add(jMenuItemingresosEgresos);

        jMenuItemInventarioPapeleria.setText("Inventario Papeleria");
        jMenuReportes.add(jMenuItemInventarioPapeleria);

        jMenuBar1.add(jMenuReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
            .addComponent(jDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearMovimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCrearMovimientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAltaProducto;
    public javax.swing.JButton jButtonCerrarSecion;
    public javax.swing.JButton jButtonCrearCategoria;
    public javax.swing.JButton jButtonCrearMovimiento;
    public javax.swing.JButton jButtonCrearUsuario;
    public javax.swing.JButton jButtonEgreso;
    public javax.swing.JButton jButtonIngreso;
    public javax.swing.JButton jButtonIngresoEgreso;
    public javax.swing.JButton jButtonInventario;
    public javax.swing.JButton jButtonMisVEntas;
    public javax.swing.JButton jButtonModificarProducto;
    public javax.swing.JButton jButtonModificarUsuario;
    public javax.swing.JButton jButtonSalor;
    public javax.swing.JButton jButtonTotal;
    public javax.swing.JButton jButtonVender;
    public javax.swing.JButton jButtonVentas;
    public javax.swing.JDesktopPane jDesktopPane;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    public javax.swing.JMenu jMenuAdministrador;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItemAltaProducto;
    public javax.swing.JMenuItem jMenuItemCerrarSeccion;
    public javax.swing.JMenuItem jMenuItemCrearCategoria;
    public javax.swing.JMenuItem jMenuItemCrearMovimiento;
    public javax.swing.JMenuItem jMenuItemCrearUsuario;
    public javax.swing.JMenuItem jMenuItemEgreso;
    public javax.swing.JMenuItem jMenuItemIngreso;
    public javax.swing.JMenuItem jMenuItemInventarioPapeleria;
    public javax.swing.JMenuItem jMenuItemMisVentas;
    public javax.swing.JMenuItem jMenuItemModificarProducto;
    public javax.swing.JMenuItem jMenuItemModificarUsuario;
    public javax.swing.JMenuItem jMenuItemSalir;
    public javax.swing.JMenuItem jMenuItemTotal;
    public javax.swing.JMenuItem jMenuItemVentasDetalle;
    public javax.swing.JMenuItem jMenuItemingresosEgresos;
    public javax.swing.JMenu jMenuMisVentas;
    public javax.swing.JMenu jMenuMovimiento;
    public javax.swing.JMenu jMenuReportes;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
